// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bd

type Articulo struct {
	ID          int32  `json:"id"`
	Titulo      string `json:"titulo"`
	Descripcion string `json:"descripcion"`
	Imagen      string `json:"imagen"`
}

type Cliente struct {
	ID       int32  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
