// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package bd

import (
	"context"
)

const createArticulo = `-- name: CreateArticulo :one
INSERT INTO articulos(titulo, descripcion, imagen) VALUES ($1, $2, $3) RETURNING id, titulo, descripcion, imagen
`

type CreateArticuloParams struct {
	Titulo      string `json:"titulo"`
	Descripcion string `json:"descripcion"`
	Imagen      string `json:"imagen"`
}

func (q *Queries) CreateArticulo(ctx context.Context, arg CreateArticuloParams) (Articulo, error) {
	row := q.db.QueryRowContext(ctx, createArticulo, arg.Titulo, arg.Descripcion, arg.Imagen)
	var i Articulo
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Imagen,
	)
	return i, err
}

const createCliente = `-- name: CreateCliente :one
INSERT INTO clientes(email, password) VALUES ($1, $2) RETURNING id, email, password
`

type CreateClienteParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateCliente(ctx context.Context, arg CreateClienteParams) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, createCliente, arg.Email, arg.Password)
	var i Cliente
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}

const deleteArticulo = `-- name: DeleteArticulo :exec
DELETE FROM articulos WHERE id = $1
`

func (q *Queries) DeleteArticulo(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteArticulo, id)
	return err
}

const deleteCliente = `-- name: DeleteCliente :exec
DELETE FROM clientes WHERE id = $1
`

func (q *Queries) DeleteCliente(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCliente, id)
	return err
}

const getArticulo = `-- name: GetArticulo :one
SELECT id, titulo, descripcion, imagen FROM articulos WHERE id = $1
`

func (q *Queries) GetArticulo(ctx context.Context, id int32) (Articulo, error) {
	row := q.db.QueryRowContext(ctx, getArticulo, id)
	var i Articulo
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Imagen,
	)
	return i, err
}

const getCliente = `-- name: GetCliente :one
SELECT id, email, password FROM clientes WHERE id = $1
`

func (q *Queries) GetCliente(ctx context.Context, id int32) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, getCliente, id)
	var i Cliente
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}

const listArticulos = `-- name: ListArticulos :many
SELECT id, titulo, descripcion, imagen FROM articulos ORDER BY titulo
`

func (q *Queries) ListArticulos(ctx context.Context) ([]Articulo, error) {
	rows, err := q.db.QueryContext(ctx, listArticulos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Articulo
	for rows.Next() {
		var i Articulo
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Imagen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientes = `-- name: ListClientes :many
SELECT id, email, password FROM clientes ORDER BY email
`

func (q *Queries) ListClientes(ctx context.Context) ([]Cliente, error) {
	rows, err := q.db.QueryContext(ctx, listClientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(&i.ID, &i.Email, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticulo = `-- name: UpdateArticulo :exec
UPDATE articulos SET titulo = $2, descripcion = $3, imagen = $4 WHERE id = $1
`

type UpdateArticuloParams struct {
	ID          int32  `json:"id"`
	Titulo      string `json:"titulo"`
	Descripcion string `json:"descripcion"`
	Imagen      string `json:"imagen"`
}

func (q *Queries) UpdateArticulo(ctx context.Context, arg UpdateArticuloParams) error {
	_, err := q.db.ExecContext(ctx, updateArticulo,
		arg.ID,
		arg.Titulo,
		arg.Descripcion,
		arg.Imagen,
	)
	return err
}

const updateCliente = `-- name: UpdateCliente :exec
UPDATE clientes SET email = $2, password = $3 WHERE id = $1
`

type UpdateClienteParams struct {
	ID       int32  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) UpdateCliente(ctx context.Context, arg UpdateClienteParams) error {
	_, err := q.db.ExecContext(ctx, updateCliente, arg.ID, arg.Email, arg.Password)
	return err
}
